### ISSUE TITLE
How return distance from distance.matrix()

### ISSUE THREAD

**Issue by sgaseretto** [ecteodoro/google-distance-matrix#15]
I'm new to node so I'm having difficulties to do something like

```javascript
const travelDistance = distance.matrix(origins, destinations, (err, distances)=> {
            if(!err) {
                const distance = distances.rows[0].elements[0].distance.text;
                return distance;
            }
        })
```

What is the correct way to get the distance and stored it in the travelDistance constant?

**Comment by ecteodoro** [comment]
You just have access to the distance inside the asynchronous block. You can try [Promises](https://www.promisejs.org/).
