### ISSUE TITLE
Using transit as Travel Mode

### ISSUE THREAD

**Issue by Pau1fitz** [ecteodoro/google-distance-matrix#6]
I am getting an error when I try and use `transit` as a travel mode.

My code looks like this:

```
var distance = require('google-distance-matrix');
distance.mode('transit');
```

I get the following error.

`Error: Invalid mode: transit`

**Comment by ecteodoro** [comment]
According to documentation: _"This value may only be specified if the request includes an API key or a Google Maps APIs Premium Plan client ID. "_
Did you check for that?

**Comment by Pau1fitz** [comment]
I don't have a Premium Plan, but i provide the API key at the top of `node js` file. Is that not enough, you don't think? 

I have stated

`distance.key('***API KEY***');`
